# Generated by Django 3.2.7 on 2021-09-24 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('title', models.CharField(max_length=1000)),
                ('review', models.CharField(max_length=1000)),
                ('image', models.ImageField(upload_to='recommend')),
            ],
        ),
    ]
