# Generated by Django 3.2.7 on 2021-09-24 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_testimonial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='profile_url',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
